### ISSUE TITLE
Submit to Crates.io

### ISSUE THREAD

**Issue by viperscape** [viperscape/rust-promise#5]
Since [Promise is already taken on crates](https://crates.io/search?q=promise), we need to rename this crate before submitting. Perhaps 
- Promises
- Promiser
- Promising

I am also unsure of nightly crates being on crates.io, so that is something to look in to as well since this will likely not build on stable quite yet

**Comment by timcharper** [comment]
It's a bummer. I saw the other implementation, and I rather prefer the direction your taking it.

Have you emailed him and see what he thinks about combining efforts? Perhaps the two libraries can be merged, and something really great can come out of it.

**Comment by viperscape** [comment]
I haven't, that's a good idea. I don't know if the other crate is under development anymore. It reminded me more of a Future than a Promise, ergonomic differences perhaps but I prefer what I started so I'm glad you agree! I'm open to all possibilities

**Comment by jsgf** [comment]
I'm using promising-future for my own take on this.

**Comment by timcharper** [comment]
I like it :-)

**Comment by viperscape** [comment]
dusted off and renamed to promiser, submitted
